name: CI

on: [ push ]

jobs:

  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
    
      - name: Get Commit Data
        id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
          cache: 'pip'
  
      - run: pip install -r requirements.txt

      - uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: crypter.pyw
          standalone: true
          onefile: true
          disable-console: true
          enable-plugins: tk-inter
          windows-icon-from-ico: ico.ico

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-${{ steps.commit.outputs.short }}
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
            LICENSE.txt
